name: BUILD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [macos-latest, windows-latest]
        arch: ["x64", "arm64"]
    steps:
      # - id: get_version
      #   uses: battila7/get-version-action@v2

      # - name: test
      #   run: echo ${{ steps.get_version.outputs.version }}

      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g yarn
          npm i -g rimraf
          yarn

      - name: Build macOS app for x64
        if: |
          matrix.os == 'macos-latest' &&
          matrix.arch == 'x64'
        run: |
          yarn make --arch=x64
        env:
          TARGET_PLATFORMS: darwin

      # - name: Build windows app
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     yarn make

      # - name: Cleanup artifacts
      #   run: |
      #     rimraf "out/make/!(*.exe|*.dmg)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: out/make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "out/make/**"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
