name: RELEASE

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [14.x]
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build mac app
        if: matrix.os == 'macos-latest'
        run: |
          npm i -g yarn
          yarn
          yarn make
        env:
          TARGET_PLATFORMS: darwin

      - name: build win app
        if: matrix.os == 'windows-latest'
        run: |
          npm i -g yarn
          yarn
          yarn make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "v1.0.3"
          prerelease: true
          files: |
            LICENSE
            out/make/*.dmg
            out/make/*.exe
