name: RELEASE

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Electron
        run: |
          npm i -g yarn
          yarn
          yarn package
        env:
          TARGET_PLATFORMS: darwin

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          title: "Unhand Studio"
          prerelease: true
          files: |
            LICENSE
            out/*.app
            out/*.exe
