name: RELEASE

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn

      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          yarn make
        env:
          TARGET_PLATFORMS: darwin

      - name: Build windows app
        if: matrix.os == 'windows-latest'
        run: |
          yarn make

      - name: Release app
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "v1.1.0"
          prerelease: true
          files: |
            out/make
